### ISSUE TITLE
Create API to ChatGPT as well as GPT?

### ISSUE THREAD

**Issue by shanelindsay** [isinaltinkaya/gptchatteR#1]
Would it be possible to add an option to interact with GPT or with ChatGPT? Rather than just GPT as present. 

ChatGPT is currently free with an unofficial API, whereas as GPT is not-free with an official API. 

e.g. see here for how to authenticate to access chatGPT

https://github.com/transitive-bullshit/chatgpt-api

**Comment by shanelindsay** [comment]
Having thought about it the issue with chatGPT is that its hard to extract the code from its output (as its markdown with code inserts). I imagine once it has an API and we also have GPT4 there will be less need for this.

**Comment by isinaltinkaya** [comment]
Hi. I agree with your comment. I do not think this would be a working solution in the long term, as they could just close ChatGPT to public use, whereas API should be more stable. But if you wish to add that functionality please feel free to contribute and send a pull request!
