### ISSUE TITLE
Suggestion for reproducible example 

### ISSUE THREAD

**Issue by shanelindsay** [isinaltinkaya/gptchatteR#2]
It took me a while to get going...as the example drew up an error for trying to run the plot (after I had created a sample df). Here is a reproducible example as a suggestion instead to have on the readme. 

library(tidyverse)
df = as.tibble
rt <- rnorm(1000, mean=700, sd=100) # Generate RT data
df <- tibble(RT = rt, group = rep(c("low", "high"), each=500)) # Create dataframe

chatter.feed("I have a dataframe df")
chatter.chat("plot histogram of rt using ggplot with df")
response = chatter.chat("plot histogram of rt using ggplot with df",return_response = TRUE)
cat(text = response$choices$text)
eval(parse(text = text))

response = chatter.chat("plot boxlots of rt using the variable group on the x axis, using ggplot",return_response = TRUE)
cat(text = response$choices$text)
eval(parse(text = text))

**Comment by isinaltinkaya** [comment]
Hi! Thank you very much for your feedback. 

I am updating the README using your examples.

However, the functionality you are describing already exists under the name `chatter.plot`.

```R
# Load the devtools package
library(devtools)

# Install the gptchatteR package from GitHub using the devtools package
install_github("isinaltinkaya/gptchatteR")

# Load the gptchatteR package
library(gptchatteR)

# Authenticate using your API key
chatter.auth("sk-qGTnjsCI8mZkCtvXVe6SUSEYOUROWNKEY")

# Create a new chat session 
chatter.create()

# Create a test data frame
library(tidyverse)
rt <- rnorm(1000, mean=700, sd=100) # Generate RT data
df <- tibble(RT = rt, group = rep(c("low", "high"), each=500))

# Feed the data frame information to the chat session
chatter.feed("I have a dataframe df")

# Use the chatter.plot function to create a histogram
chatter.plot("plot histogram of rt using ggplot with df")
```

Please feel free to reopen the issue if this doesn't help!

Best wishes,
Isin

**Comment by shanelindsay** [comment]
Great. 
The chatterplot example for me leads to this error:
Error in str2lang(s) : parsing result not of length one, but 2

The idea behind my code was to just to illustrate running code not specifically plotting functionality. I just wanted to see what the string was given by openai and then execute it. 

For example it could be:
response = chatter.chat("Report the average of RT for each group",return_response = TRUE)
text = response$choices$text
cat(text)
eval(parse(text = text))

(though in this example it includes a plot a histogram in the openai response which I don't quite understand)
