### ISSUE TITLE
basic error with your example

### ISSUE THREAD

**Issue by ikohane** [isinaltinkaya/gptchatteR#6]
> library(devtools)
Loading required package: usethis
> install_github("isinaltinkaya/gptchatteR")
...
* DONE (gptchatteR)
> library(gptchatteR)
Loading required package: openai
> chatter.auth("XXXXXXXXXXXXXXXX")
> chatter.chat("Hello, ChatGPT!")
Error in chatter.chat("Hello, ChatGPT!") : 
  could not find function "chatter.chat"

Any idea what I am doing incorrectly?

**Comment by isinaltinkaya** [comment]
Hi!

You need to first create the chatter using:

```
chatter.create()
```

right after authenticating the chatter with your key.

Best,
Isin
